### ISSUE TITLE
New botConfig option to accept text reportbacks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-campaigns#1021]
_FEATURE OVERVIEW_
-------------------
#### User Story
As an admin, I want the option to configure a campaign to collect and submit a Rogue post with type `'text'`, instead of current type `'photo'`.  

#### Links
* https://www.pivotaltracker.com/story/show/155988891
*  [Spec](https://docs.google.com/document/d/1VjpgRTeVakbbSr1WwkR4tEjXiiVZ9i1bAEkNInsWQrk/edit?usp=sharing)

#### Tasks

*Contentful:*
* [x] Create a new `textPostTemplate` content type in Gambini, with multi-line text fields `askTextMessage` and `invalidTextMessage`
* [x] Create a new `postTemplate` field on a Gambini campaign, as a reference field accepting only `textPostTemplate` entries.

*GET /campaigns:*
* [x] Add `askText` and `invalidText` properties to response `templates` object

*POST /receive-message:*

If Campaign has `postTemplate` set to a `textPostTemplate`:
*  [x] Send response with `replyTemplate` set as  `'invalidText'` if the message text is not valid or contains only emoji
*  [x] if valid, create a signup and post with type `'text'`  and send response with `replyTemplate` set as `'completedMenu'`

#### Additional information

We'll want to create a `photoPostTemplate` content type and migrate the relevant Campaign fields like `askPhoto`, `askQuantity`. Not needed for launching support for text campaign posts.

**Comment by aaronschachter** [comment]
Final task resolved in https://github.com/DoSomething/gambit-campaigns/pull/1035.
