### ISSUE TITLE
5.0.0 cleanup

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit-campaigns#989]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a developer, I want to remove all code that won't be used in production when Conversations is live.

#### Tasks

* [x] Delete `BotRequest` model - #1007 
* [x] Delete `User` model - #1002 
* [x] Delete `logs` winston collection
* [x] Delete `POST /campaign/:id/message`  route - #998
* [x] Delete `POST /chatbot` route - #998 
* [x] Delete `POST /signups` route - #998 
* [x] Move middleware used by `receive-message` into a `receive-message` directory, delete middleware no longer used, e.g. `user-get` - #1009 
* [x] Delete `lib/consolebot` ? - #1001 
* [x] Delete `/lib/groups` - #996 
* [x] Delete `/lib/mobilecommons` - #1007 
* [x] Delete `lib/northstar` - #1004 
* [x] Refactor `lib/conversation` - #1007, #1009 
* [x] Deprecate `lib/middleware/map-request-params` - #1005 
* [x] Remove unused helpers - #1008 
* [x] Move relevant tests into Gambit Campaigns
